unbind C-b
set -g prefix `
bind-key ` last-window
bind-key e send-prefix

set -g status-position bottom

set -g mode-keys vi
set -g status-keys vi
set-option -g history-limit 5000

set -g status-right ""
set -g status-left ""

set -g status-justify centre

set -g status-bg colour234
set -g status-fg colour137

setw -g window-status-current-format ' #I#[fg=colour250]:#[fg=colour255]#W#[fg=colour50]#F '
setw -g window-status-format ' #I#[fg=colour237]:#[fg=colour250]#W#[fg=colour244]#F '

#set-option -sg escape-time 10
set-option -g allow-passthrough on
